// ── SENTINEL TERMINAL GRAPH STYLES (Stitch Design System) ────────────────────
// Based on the SENTINEL Terminal design system generated by Stitch MCP

export const STATUS_STYLES = {
  active:    { bg: '#0284C7', border: '#0369A1', icon: '●' },
  flagged:   { bg: '#D97706', border: '#B45309', icon: '⚠' },
  frozen:    { bg: '#334155', border: '#475569', icon: '🔒' },
  withdrawn: { bg: '#991B1B', border: '#DC2626', icon: '✕' }
};

export const TYPE_STYLES = {
  SOURCE:       { bg: '#1E3A8A', border: '#3B82F6', badge: 'SOURCE',    shape: 'ellipse' },
  MULE:         { bg: '#7F1D1D', border: '#EF4444', badge: 'MULE',      shape: 'octagon' },
  INTERMEDIARY: { bg: '#78350F', border: '#F59E0B', badge: 'HUB',       shape: 'round-rectangle' },
  DESTINATION:  { bg: '#581C87', border: '#A78BFA', badge: 'EXIT',      shape: 'pentagon' },
  SUSPECT:      { bg: '#881337', border: '#FB7185', badge: 'SUSPECT',   shape: 'octagon' },
  VICTIM:       { bg: '#1E3A8A', border: '#3B82F6', badge: 'VICTIM',    shape: 'ellipse' }
};

export const NODE_SHAPE_MAP = {
  victim:     'ellipse',
  mule:       'octagon',
  merchant:   'round-rectangle',
  UPI:        'diamond',
  cashout:    'pentagon',
  crypto:     'hexagon',
  collector:  'round-rectangle',
  individual: 'ellipse'
};

export const NODE_BG_MAP = {
  victim:     '#1E3A8A',
  mule:       '#7F1D1D',
  merchant:   '#064E3B',
  UPI:        '#4C1D95',
  cashout:    '#7F1D1D',
  crypto:     '#4C1D95',
  collector:  '#78350F',
  individual: '#0C4A6E'
};

export const NODE_BORDER_MAP = {
  victim:     '#60A5FA',
  mule:       '#F87171',
  merchant:   '#34D399',
  UPI:        '#C084FC',
  cashout:    '#FCA5A5',
  crypto:     '#A78BFA',
  collector:  '#FBBF24',
  individual: '#38BDF8'
};

export const graphStyles = [
  {
    selector: 'node',
    style: {
      'shape': (node) => {
        const ntype = node.data('node_type');
        if (ntype && NODE_SHAPE_MAP[ntype]) return NODE_SHAPE_MAP[ntype];
        const atype = node.data('account_type');
        if (atype && TYPE_STYLES[atype]) return TYPE_STYLES[atype].shape;
        return 'ellipse';
      },
      'label': (node) => {
        const id = node.data('displayLabel') || node.data('accountId') || node.data('id') || '';
        const ntype = (node.data('node_type') || node.data('account_type') || 'ACCT').toUpperCase();
        const shortId = String(id).length > 12 ? String(id).slice(0, 12) + '…' : String(id);
        return `${shortId}\n${ntype}`;
      },
      'background-color': (node) => {
        const status = node.data('status');
        if (status === 'frozen') return '#1E293B';
        const ntype = node.data('node_type');
        if (ntype && NODE_BG_MAP[ntype]) return NODE_BG_MAP[ntype];
        const atype = node.data('account_type');
        if (atype && TYPE_STYLES[atype]) return TYPE_STYLES[atype].bg;
        return '#1E3A8A';
      },
      'border-width': 2.5,
      'border-color': (node) => {
        const status = node.data('status');
        if (status === 'frozen') return '#475569';
        if (status === 'flagged') return '#F59E0B';
        const ntype = node.data('node_type');
        if (ntype && NODE_BORDER_MAP[ntype]) return NODE_BORDER_MAP[ntype];
        const atype = node.data('account_type');
        if (atype && TYPE_STYLES[atype]) return TYPE_STYLES[atype].border;
        return '#38BDF8';
      },
      'border-style': 'solid',
      'background-opacity': 0.85,
      'color': '#F0F9FF',
      'text-valign': 'center',
      'text-halign': 'center',
      'text-wrap': 'wrap',
      'text-max-width': 72,
      'font-size': 9.5,
      'font-family': 'JetBrains Mono, monospace',
      'font-weight': '500',
      'width': 76,
      'height': 76,
      'text-outline-width': 2,
      'text-outline-color': '#020617',
      'overlay-opacity': 0,
      'transition-property': 'background-color, border-color, border-width, width, height, opacity',
      'transition-duration': '0.2s'
    }
  },
  {
    selector: 'edge',
    style: {
      'label': (edge) => {
        const amt = Number(edge.data('amount') || 0);
        const formatted = new Intl.NumberFormat('en-IN').format(Math.round(amt));
        const ch = edge.data('channel') || 'UPI';
        const hop = edge.data('hop_number') || 1;
        const totalHops = edge.data('total_hops') || '';
        return `₹${formatted} · ${ch} · H${hop}${totalHops ? '/' + totalHops : ''}`;
      },
      'width': (edge) => edge.data('suspicious') ? 3.5 : 2.5,
      'line-color': (edge) => edge.data('suspicious') ? '#EF4444' : '#38BDF8',
      'target-arrow-color': (edge) => edge.data('suspicious') ? '#EF4444' : '#38BDF8',
      'line-style': (edge) => edge.data('suspicious') ? 'dashed' : 'solid',
      'line-dash-pattern': [8, 4],
      'target-arrow-shape': 'triangle',
      'arrow-scale': 1.3,
      'curve-style': 'bezier',
      'control-point-step-size': 60,
      'font-size': 9,
      'font-family': 'JetBrains Mono, monospace',
      'font-weight': '500',
      'color': '#CBD5E1',
      'text-rotation': 'autorotate',
      'text-margin-y': -11,
      'text-background-color': '#020617',
      'text-background-opacity': 0.9,
      'text-background-padding': '3px',
      'text-border-color': '#1E293B',
      'text-border-width': 1,
      'text-border-opacity': 1,
      'opacity': 0.92,
      'transition-property': 'line-color, target-arrow-color, width, opacity',
      'transition-duration': '0.2s'
    }
  },
  {
    // Selected node - subtle blue glow
    selector: 'node:selected',
    style: {
      'border-width': 4,
      'border-color': '#38BDF8',
      'width': 88,
      'height': 88
    }
  },
  {
    // Selected edge
    selector: 'edge:selected',
    style: {
      'width': 4.5,
      'line-color': '#38BDF8',
      'target-arrow-color': '#38BDF8'
    }
  },
  {
    selector: 'node.path-highlight',
    style: {
      'border-width': 5,
      'border-color': '#38BDF8',
      'background-opacity': 1,
      'z-index': 60
    }
  },
  {
    selector: 'edge.path-highlight',
    style: {
      'width': 5,
      'line-color': '#38BDF8',
      'target-arrow-color': '#38BDF8',
      'opacity': 1,
      'z-index': 60,
      'line-style': 'solid',
      'text-background-color': '#0C4A6E',
      'text-border-color': '#38BDF8',
      'text-border-width': 1
    }
  },
  {
    selector: 'edge.new-transaction-pulse',
    style: {
      'width': 5.5,
      'line-color': '#EF4444',
      'target-arrow-color': '#EF4444',
      'opacity': 1,
      'z-index': 100,
      'text-background-color': '#7F1D1D',
      'text-border-color': '#EF4444',
      'text-border-width': 1.5
    }
  },
  {
    selector: '.dimmed',
    style: {
      'opacity': 0.15
    }
  }
];
